### ISSUE TITLE
some question about testing the model

### ISSUE THREAD

**Issue by UltraBald** [jabhinav/Prompt-Tuning-Strikes-Back-with-LOPA-NLU#1]
Could you please provide the code for testing the final model, rather than the code for obtaining results on the validation set

**Comment by jabhinav** [comment]
Hi, we have updated the script eval.py. The ReadMe has also been updated, providing instructions on how to test your model. You can now generate predictions (i.e. classification labels) and compute evaluation metrics. 

Note. The current implementation assumes that the test split of the glue benchmark does not have G.T. labels. Thus, you can only generate predictions on it.
